### ISSUE TITLE
Multiple timers

### ISSUE THREAD

**Issue by tatarinov1997** [Darkyenus/DarkyenusTimeTracker#10]
In PyCharm, if I open another project in the current window, the previous project timer is still on the screen, as well as current one. 
Steps to reproduce:
Open project with timer enabled
Go to File->Open Recent-> Choose another project with enabled timer -> Open in current window
![timers](https://cloud.githubusercontent.com/assets/17722304/24580846/77685ff8-1718-11e7-88be-6afeb7b00c25.png)

**Comment by Darkyenus** [comment]
Can reproduce, thanks for the report
