### ISSUE TITLE
Feature Request: Optional Pause on Loss of Focus

### ISSUE THREAD

**Issue by Mochnant** [Darkyenus/DarkyenusTimeTracker#14]
It would be useful if there were an option to pause when program focus is lost.  Some may prefer to count time when they are doing other things, but I prefer not.

This would also cover issues when multiple timers in different open projects are going simultaneously.

**Comment by Mochnant** [comment]
Would also be a good enhancement to give the option to automatically resume when focus is regained.

**Comment by Darkyenus** [comment]
*This was probably not possible by the time this was reported, but it is now, for quite some time. Following reply is mostly for completeness.*

In recent versions, idle timer setting can be used to specify the duration for which the counter should keep counting after focus is lost. When there are multiple timers in multiple IDE windows (of the same IDE process), activating one will automatically pause others (unless this functionality is disabled in settings). Paused timer is automatically started when window regains focus or on mouse movement (when paused by timeout).

**Comment by Mochnant** [comment]
Thank you, @Darkyenus!
