### ISSUE TITLE
Collaboration offer: Consume logs from website

### ISSUE THREAD

**Issue by romafederico** [Darkyenus/DarkyenusTimeTracker#18]
Hi there! It'll be interesting if you could send a post request with logged times to a server so users could sign in and see their logged times on a website. Just like wakatime. 

I can take care of the website if you want to work together with this!

**Comment by Darkyenus** [comment]
I'm planning a large update/rewrite in the future (when I get around to it) and it has currently greater priority than this.

The idea is interesting, but who would use it and why? I'm guessing it would be for teams, long term statistics and backup, maybe? How would it be different from wakatime? (There is no point in making something that already exists and is better.) I guess that each user would have to host their own website, if we want to stay free (and if not, then this becomes really just a worse wakatime).
