### ISSUE TITLE
Bugs in 1.4 - wrong counter

### ISSUE THREAD

**Issue by mice777** [Darkyenus/DarkyenusTimeTracker#21]
After update, the plugin started to misbehave.

When I switch projects in Android Studio (File -> Open recent), the counter is not taken from loaded project, but remains from previous project. Also the green counter on bottom bar is then placed on left side, while it is on right-most position if loaded normally.

During project loading I even see 2 counters, the right being correct:
![image](https://user-images.githubusercontent.com/3145438/45927303-a5288900-bf31-11e8-9441-4955734f3465.png)
but later the right counter disappears.

Previous version (1.3.6?) worked correctly.

**Comment by mice777** [comment]
I'm not sure if only visual. I see only counter from previous project, not actual counter, and in wrong position. I don't know if correct counter is even there.

See the wrong counter after new project loads:

![image](https://user-images.githubusercontent.com/3145438/45949920-e7b79780-bffd-11e8-9807-de27ff1ea6c8.png)

**Comment by Scott-G** [comment]
I have done some testing and it seems that the widget is still recording correctly (and even offers to count away time) for the current project but the counter from the previous project is remaining displayed (albeit in a different position) rather than the current counter.
