### ISSUE TITLE
Where is the file stored ?

### ISSUE THREAD

**Issue by stasbar** [Darkyenus/DarkyenusTimeTracker#22]
Hello,
I just switched from Android Studio 3.2 to 3.3 and all my times from projects disappeared. Could you please tell me where the files are stored, so I can copy them to new Android Studio preferences folder ?

**Comment by Darkyenus** [comment]
Titular question is [now](ea34d06ee43835a891fc54c23a942e2a945f7a0a) fully explained in the README.
