### ISSUE TITLE
Feature Request: Hotkey for resetting time

### ISSUE THREAD

**Issue by netqsander** [Darkyenus/DarkyenusTimeTracker#28]
Thanks a lot for this lightweight, valuable plugin. The only feature I am missing is a hotkey or other shortcut to reset the time. Would it be possible to add this?

**Comment by Darkyenus** [comment]
Added in e5066646ed9477d39b026426e4f23e405b030b21, it should be out today or tomorrow. There are no default shortcuts or menus where it appears (as I don't want to clutter the interface for those that don't need it), but you can give it a custom shortcut, add it to any menu (both is done from IDE's preferences), or just invoke it from search everything.

**Comment by netqsander** [comment]
A very elegant solution, thanks!
