### ISSUE TITLE
Question: Tracking time spent running tests

### ISSUE THREAD

**Issue by Silverlight42** [Darkyenus/DarkyenusTimeTracker#49]
First of all, thanks for the plugin!

Now the question is: it possible to track time spent running/debugging tests?

Thanks.

**Comment by Darkyenus** [comment]
No, the plugin has no knowledge about what is going on in the editor, except for listening for low-level input events for activity detection. And there is not even any system into which the recorded time could be meaningfully added (yet?), the plugin has just the single visible time counter.

**Comment by Silverlight42** [comment]
Understood. Thanks for answering!
