### ISSUE TITLE
With Git Integration, reset time on commit

### ISSUE THREAD

**Issue by CameronJ** [Darkyenus/DarkyenusTimeTracker#8]
With the git integration, I have an enhancement request: when it automatically injects the time into the commit messages, can it reset the time automatically?  It seems to me, the the intent of the feature is to log the amount of time it took to complete the commit.  However, following this example:
1) work on a something for 2 hours
2) execute a commit
3) inject the commit message: "Took 2 hours"
4) work for 5 more minutes
5) execute a commit
6) inject the commit message: "Took 2 hours 5 minutes"

Again, to me it seems like the commit message in Step 6, should likely say "5 minutes", since that commit really took the difference between that commit, and the prior.

**Comment by Darkyenus** [comment]
What you described is the intended behavior (and what happens on my machine). What platform are you on? Looks like a bug in the git hook script, more specifically [here](https://github.com/Darkyenus/DarkyenusTimeTracker/blob/master/resources/hooks/prepare-commit-msg#L52).

**Comment by CameronJ** [comment]
I'm running Mac OS 10.11, sorry for the delay

**Comment by Darkyenus** [comment]
I'm also on 10.11(.6), I'm not sure what could cause that, I'll need some more info/help with this one.
- Are you on the latest plugin version? What is the content of `.git/hooks/prepare-commit-msg`?
- Does this happen always? (I assume it does, but just in case this is some sort of race condition)
- Can you check the contents and access rights of `.git/.darkyenus_time_tracker_commit_time`, especially before/after commit?
- Does `git commit` print any additional info (vs non-tracked projects)? It should at least print how much time it took/that it took no time.

**Comment by CameronJ** [comment]
Again, sorry for the delay, haven't had any work to do in IntelliJ recently...

I just did an update today to the latest version (looks like you recently updated the version).

Before the commit, I see the contents of `.git/.darkyenus_time_tracker_commit_time` as `152`.
After the commit, I see the contents as `177`.
Access rights have not changed, owner is myself with `rw-` permission.

The contents of `.git/hooks/prepare-commit-msg` is below:
```
#!/bin/bash

# Identifier, do not change if modifying:
#DarkyenusTimeTrackerHookScript00003

# Script (can be modified, but may be overwritten if new plugin version is installed):

if [ "$2" = "merge" ] || [ "$2" = "squash" ]
then
	echo "Not injecting time into $2 commit"
	exit 0
fi

# Do not append time if the commit message is empty, because such commit will not happen
COMMIT_MESSAGE_LINES=$(cat "$1" | sed -e '/^#.*$/ d' -e '/^[[:space:]]*$/ d' | wc -l)
if [ "$2" = "message" ] && (($COMMIT_MESSAGE_LINES == 0))
then
	echo "Not injecting time into cancelled commit"
	exit 0
fi

# Do not append time to amend commits - those already may have the time appended.
# The only way to detect amend commit is the check whether or not the first line of commit message is empty.
# That however does not work for "message" type commits (commit -m), but that is not a big deal,
# as those won't have the time appended anyway, so they are not problematic.
FIRST_COMMIT_LINE=$(head -n 1 "$1")
if [ "$2" == "commit" ] && [ -n "$FIRST_COMMIT_LINE" ]
then
	echo "Not injecting time into amend commit"
	exit 0
fi

DTT_TIME="$(dirname "$0")/../.darkyenus_time_tracker_commit_time"

if [ -e "$DTT_TIME" ]
then
	TIME_TOTAL_SEC=$(cat ${DTT_TIME})
	TIME_REMAINING_SEC="$TIME_TOTAL_SEC"
	TIME_MESSAGE=""
	if (($TIME_TOTAL_SEC >= 3600))
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 3600)) hour"
		if (($TIME_REMAINING_SEC / 3600 != 1))
		then
		    TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
		TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 3600))
	fi

	if (($TIME_TOTAL_SEC >= 60))
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 60)) minute"
		if (($TIME_REMAINING_SEC / 60 != 1))
		then
			TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
        TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 60))
	fi

	if (($TIME_TOTAL_SEC > 0))
	then
		if (($TIME_TOTAL_SEC < 60))
		then
			TIME_MESSAGE="$TIME_MESSAGE $TIME_REMAINING_SEC second"
			if (($TIME_REMAINING_SEC != 1))
	        then
	            TIME_MESSAGE="${TIME_MESSAGE}s"
	        fi
        fi

        printf "\n\nTook$TIME_MESSAGE" >> "$1"
        echo "0" > "$DTT_TIME"
        echo "Commit took$TIME_MESSAGE"
    else
        echo "Commit took no time, not recording"
	fi
else
	echo "No timing data found"
fi
```

I just did the commit from within IntelliJ and not via command prompt and this was what was displayed in the Version Control Console:
```
git -c core.quotepath=false commit --only -F /private/var/folders/ft/6qvcjcbd6zs55vj38qbjs2pw0000gn/T/git-commit-msg-.txt -- views/assets/js/tmp_panels.js views/assets/js/modules/panel.js
[feature/v2 f30028a] AVS-75
 2 files changed, 8 insertions(+), 2 deletions(-)
```

Here is the Git Log output:
```
commit f30028a305fb91bf00307a9ce59dd6d3dcedd333
Author: CameronJ <email removed>
Date:   Tue Apr 25 18:48:30 2017 -0700

    AVS-75
    
    Took 2 minutes
```

**Comment by CameronJ** [comment]
Oh, sorry, I missed answering a question, yes it seems to do this every time.

**Comment by jIRKA-232** [comment]
That's weird.
Can you try replacing lines
```
        echo "0" > "$DTT_TIME"
        echo "Commit took$TIME_MESSAGE"
```
with this:
```
        printf "0" > "$DTT_TIME"
        printf "Commit took$TIME_MESSAGE\n"
```

Thanks.

**Comment by Darkyenus** [comment]
This looks like a problem with bash/aliases/setup, something like that. If what jIRKA-232 suggested doesn't work (or even if it does), can you please try `type -a echo` ?

**Comment by CameronJ** [comment]
```
$ type -a echo
echo is a shell builtin
echo is /bin/echo
```

**Comment by CameronJ** [comment]
I made the change to switch `echo` with `printf`, and it still seems to be injecting the commit messages properly, but not reseting the time.

**Comment by Darkyenus** [comment]
Does it reset the time correctly when you do the `echo "0" > ".git/.darkyenus_time_tracker_commit_time"` manually? This is so strange.

**Comment by CameronJ** [comment]
ah, great question, I'll give that shot right now.
before:
![image](https://cloud.githubusercontent.com/assets/1232011/25551341/3f77a326-2c38-11e7-9226-7b398de5048c.png)

after:
![image](https://cloud.githubusercontent.com/assets/1232011/25551347/51384462-2c38-11e7-8843-dbf298f030a7.png)

**Comment by Darkyenus** [comment]
Maybe some problems with escaping? What is the full path to the repo? (You can replace alphanumerics for anonymity, I'm interested in spaces and other special symbols). Otherwise, I have no idea.

**Comment by CameronJ** [comment]
`/Users/cameronj***/Sites/A***/Dashboard.Avesse.com`

put ***'s in instead of some of the alphanumerics in the path.   Also, just an FYI "Sites" is a Symbolic Link to:
`/Users/cameronj*/Dropbox/Sites`

**Comment by CameronJ** [comment]
Yeah, trust me, I'm quite as dumbfounded as you.  Honestly, based on the test you had me run earlier... it leads me to believe that whatever part of the plugin that is monitoring the contents of `.git/darkyenus_time_tracker_commit_time` in order to update the counter on the bottom of the window, is likely the culprit here.  I assume that's something that's actually built into the plugin, rather than a git hook.  Is there anyway to try and trace that?

**Comment by Darkyenus** [comment]
One would think that, but the plugin does no trace content of that file at all. All it does is that when it decides that it is time to save, it loads the file reads its content, converts it into number adds how many seconds elapsed since last save and saves that number back into the file. External modifications to the file are not propagated back into the plugin. That way, git commit will correctly append elapsed time whether or not the plugin is running. (Yeah, there should be some sort of locking, but since you said that it happens every time, that should not be the case.)

Does `git commit` produce line with something like `echo "Commit took$TIME_MESSAGE"`? It appears that [it can silently fail and exit](http://stackoverflow.com/questions/37434448/how-can-i-prevent-i-o-redirection-from-silently-failing-upon-modifying-the-file), but I am not sure under what circumstances. Does it happen in projects that don't have symlink in their path and when commiting when IDE is completely closed?

**Comment by evgarik** [comment]
#3 Stopping the plugin, the time is reset and everything works.
It is not convenient to stop each time

**Comment by Darkyenus** [comment]
I have just experienced the same problem, so something is definitely wrong.

I suspect that it could be because IntelliJ has the file open at the same time as the commit happens, but otherwise I am not sure.

**Comment by mkrauser** [comment]
I have the same issue. If I run the echo-test, the time does not reset, no matter if I stopped the timer or not.

If there's anything I can do, just let me know.

**Comment by Darkyenus** [comment]
@mkrauser So `echo "0" > ".git/.darkyenus_time_tracker_commit_time"` does not change the file, but the file contains validly incremented amount of seconds in commit? Hmm. Which OS are you on and are you on latest version?

**Comment by Darkyenus** [comment]
I have made the script much more robust (hopefully) in fac26fd036123363295a747721056d3bb910cc4f and I am pretty sure that this issue is resolved. Reopen if it happens again.
